bot:
  server: "https://synapse.example.com"
  username: "registerbot"
  access_token: "verysecret"
api:
  # API endpoint of the registration tokens
  base_url: 'https://synapse.example.com/_synapse/admin/v1/registration_tokens'
  # Access token of an administrator on the server
  token: "supersecret"

