---

- import_tasks: "{{ role_path }}/tasks/validate_config.yml"
  when: "run_setup|bool and matrix_registration_bot_enabled|bool"
  tags:
    - setup-all
    - setup-matrix-registration-bot

- import_tasks: "{{ role_path }}/tasks/setup_install.yml"
  when: "run_setup|bool and matrix_registration_bot_enabled|bool"
  tags:
    - setup-all
    - setup-matrix-registration-bot
